apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
type: Opaque
data:
  SERVER_PORT: {{ .Values.SECRET.SERVER_PORT | b64enc | quote }}
  SPRING_PROFILES_ACTIVE: {{ .Values.SECRET.SPRING_PROFILES_ACTIVE | b64enc | quote }}
  LOG_LEVEL: {{ .Values.SECRET.LOG_LEVEL | b64enc | quote }}
  VCLIPPING_TEST_VIDEOS_DIR: {{ .Values.SECRET.VCLIPPING_TEST_VIDEOS_DIR | b64enc | quote }}
  VCLIPPING_OUTPUT_DIR: {{ .Values.SECRET.VCLIPPING_OUTPUT_DIR | b64enc | quote }}
  VCLIPPING_TEMP_DIR: {{ .Values.SECRET.VCLIPPING_TEMP_DIR | b64enc | quote }}
  VCLIPPING_TEST_VIDEO: {{ .Values.SECRET.VCLIPPING_TEST_VIDEO | b64enc | quote }}
  FFMPEG_PATH: {{ .Values.SECRET.FFMPEG_PATH | b64enc | quote }}
  FFPROBE_PATH: {{ .Values.SECRET.FFPROBE_PATH | b64enc | quote }}
  VCLIPPING_ALLOWED_FORMATS: {{ .Values.SECRET.VCLIPPING_ALLOWED_FORMATS | b64enc | quote }}
  VCLIPPING_DEFAULT_FORMAT: {{ .Values.SECRET.VCLIPPING_DEFAULT_FORMAT | b64enc | quote }}
  VCLIPPING_MAX_FILE_SIZE_MB: {{ .Values.SECRET.VCLIPPING_MAX_FILE_SIZE_MB | b64enc | quote }}
  VCLIPPING_MAX_DURATION_SECONDS: {{ .Values.SECRET.VCLIPPING_MAX_DURATION_SECONDS | b64enc | quote }}
  VCLIPPING_DEFAULT_FPS: {{ .Values.SECRET.VCLIPPING_DEFAULT_FPS | b64enc | quote }}
  VCLIPPING_DEFAULT_IMAGE_FORMAT: {{ .Values.SECRET.VCLIPPING_DEFAULT_IMAGE_FORMAT | b64enc | quote }}
  VCLIPPING_DEFAULT_COMPRESSION: {{ .Values.SECRET.VCLIPPING_DEFAULT_COMPRESSION | b64enc | quote }}
  VCLIPPING_JPEG_QUALITY: {{ .Values.SECRET.VCLIPPING_JPEG_QUALITY | b64enc | quote }}
  VCLIPPING_MAINTAIN_ASPECT_RATIO: {{ .Values.SECRET.VCLIPPING_MAINTAIN_ASPECT_RATIO | b64enc | quote }}
  AWS_ACCOUNT_ID: {{ .Values.SECRET.AWS_ACCOUNT_ID | toString | b64enc | quote }}
  AWS_REGION: {{ .Values.SECRET.AWS_REGION | b64enc | quote }}
  AWS_S3_BUCKET: {{ .Values.SECRET.AWS_S3_BUCKET | b64enc | quote }}
  AWS_S3_INPUT_PREFIX: {{ .Values.SECRET.AWS_S3_INPUT_PREFIX | b64enc | quote }}
  AWS_S3_OUTPUT_PREFIX: {{ .Values.SECRET.AWS_S3_OUTPUT_PREFIX | b64enc | quote }}
  AWS_S3_TEMP_PREFIX: {{ .Values.SECRET.AWS_S3_TEMP_PREFIX | b64enc | quote }}
  AWS_SQS_PROCESSING_QUEUE_URL: {{ .Values.SECRET.AWS_SQS_PROCESSING_QUEUE_URL | b64enc | quote }}
  AWS_SQS_RESULT_QUEUE_URL: {{ .Values.SECRET.AWS_SQS_RESULT_QUEUE_URL | b64enc | quote }}
  VCLIPPER_PROCESSING_API_URL: {{ .Values.SECRET.VCLIPPER_PROCESSING_API_URL | b64enc | quote }}
  API_TIMEOUT_SECONDS: {{ .Values.SECRET.API_TIMEOUT_SECONDS | b64enc | quote }}
  API_RETRY_ATTEMPTS: {{ .Values.SECRET.API_RETRY_ATTEMPTS | b64enc | quote }}
