
IMAGE:
  REPOSITORY: 171219910203199431032017/vclipping
  TAG: latest
  PULL_POLICY: Always

HPA:
  ENABLED: true
  MAXREPLICAS: 3
  CPU: 90
  MEMORY: 1600Mi

INGRESS:
  ENABLED: false
  HOST: api.vclipping.com.br
  GATEWAY: ingress-gw
  PREFIX: /
  
DEPLOYMENT:
  REPLICAS: 2
  PORT: 8080
  STRATEGY:
    MAXSURGE: 1
    MAXUNAVAILABLE: 1
    TYPE: RollingUpdate
  ENV:
    ENABLED: true

  TOLERATIONS:
    ENABLED: false
    KEY: application
    OPERATOR: Equal
    VALUE: vclipper-app
    EFFECT: NoSchedule
  NODESELECTOR:
    ENABLED: false
    KEY: application
    VALUE: vclipper-app
  RESOURCES:
    MIN:
      CPU: 100m
      RAM: 256Mi
    MAX:
      RAM: 1600Mi
  
  LIVENESSPROBE:
    ENABLED: false
    PATH: /actuator/health
    INITIALDELAY: 120
    PERIOD: 10
    FAILURETHRESHOLD: 3

  READINESSPROBE:
    ENABLED: false
    INITIALDELAY: 30
    PERIOD: 10
    FAILURETHRESHOLD: 3

SERVICE:
  TYPE: ClusterIP
  PORT: 80
  INTERNAL: false
  HTTPS:
    ENABLED: false
  LOAD_BALANCER:
    ENABLED: true
    DNS_SUFFIX: api.vclipper.com.br
    

SECRET:
  TZ: "America/Sao_Paulo"
  SERVER_PORT: "8080"
  SPRING_PROFILES_ACTIVE: "mock"
  LOG_LEVEL: "INFO"
  VCLIPPING_TEST_VIDEOS_DIR: "./test_videos"
  VCLIPPING_OUTPUT_DIR: "./output"
  VCLIPPING_TEMP_DIR: "./temp"
  VCLIPPING_TEST_VIDEO: "VID_20250301_104432.mp4"
  FFMPEG_PATH: "ffmpeg"
  FFPROBE_PATH: "ffprobe"
  VCLIPPING_ALLOWED_FORMATS: "mp4,avi,mov,wmv"
  VCLIPPING_DEFAULT_FORMAT: "mp4"
  VCLIPPING_MAX_FILE_SIZE_MB: "500"
  VCLIPPING_MAX_DURATION_SECONDS: "3600"
  VCLIPPING_DEFAULT_FPS: "1.0"
  VCLIPPING_DEFAULT_IMAGE_FORMAT: "PNG"
  VCLIPPING_DEFAULT_COMPRESSION: "ZIP"
  VCLIPPING_JPEG_QUALITY: "85"
  VCLIPPING_MAINTAIN_ASPECT_RATIO: "true"
  AWS_ACCOUNT_ID: "879956639231"
  AWS_REGION: "us-east-1"
  AWS_S3_BUCKET: "vclipper-video-storage-prod"
  AWS_S3_INPUT_PREFIX: "videos/"
  AWS_S3_OUTPUT_PREFIX: "vclipping-frames/"
  AWS_S3_TEMP_PREFIX: "temp/vclipping/"
  AWS_SQS_PROCESSING_QUEUE_URL: "https://sqs.us-east-1.amazonaws.com/879956639231/vclipper-video-processing-prod"
  AWS_SQS_RESULT_QUEUE_URL: "https://sqs.us-east-1.amazonaws.com/879956639231/vclipper-vclipping-results-prod"
  VCLIPPER_PROCESSING_API_URL: "http://vclipper-processing.prod.svc.cluster.local"
  API_TIMEOUT_SECONDS: "30"
  API_RETRY_ATTEMPTS: "3"
