
IMAGE:
  REPOSITORY: 171219910203199431032017/vclipper
  TAG: latest
  PULL_POLICY: Always

HPA:
  ENABLED: true
  MAXREPLICAS: 3
  CPU: 90
  MEMORY: 400Mi

INGRESS:
  ENABLED: false
  HOST: api.vclipper.com.br
  GATEWAY: ingress-gw
  PREFIX: /
  
DEPLOYMENT:
  REPLICAS: 2
  PORT: 8080
  STRATEGY:
    MAXSURGE: 1
    MAXUNAVAILABLE: 1
    TYPE: RollingUpdate
  ENV:
    ENABLED: true

  TOLERATIONS:
    ENABLED: false
    KEY: application
    OPERATOR: Equal
    VALUE: vclipper-app
    EFFECT: NoSchedule
  NODESELECTOR:
    ENABLED: false
    KEY: application
    VALUE: vclipper-app
  RESOURCES:
    MIN:
      CPU: 50m
      RAM: 12Mi
    MAX:
      RAM: 500Mi
  
  LIVENESSPROBE:
    ENABLED: false
    PATH: /actuator/health
    INITIALDELAY: 120
    PERIOD: 10
    FAILURETHRESHOLD: 3

  READINESSPROBE:
    ENABLED: false
    INITIALDELAY: 30
    PERIOD: 10
    FAILURETHRESHOLD: 3

SERVICE:
  TYPE: ClusterIP
  PORT: 80
  INTERNAL: false
  HTTPS:
    ENABLED: false
  LOAD_BALANCER:
    ENABLED: true
    DNS_SUFFIX: api.vclipper.com.br
    

SECRET:
  SERVER_PORT: 8080
  DB_HOST: vclipper-hackaton-prod.0acxv.mongodb.net
  DB_PORT: 27017
  MONGODB_DATABASE: vclipper
  MONGODB_USER: vclipperuser
  MONGODB_PASSWORD: vclipper01
  MONGO_INITDB_ROOT_USERNAME: mongodbadmin
  MONGO_INITDB_ROOT_PASSWORD: admin
  MONGO_INITDB_DATABASE: vclippe

  MAX_FILE_SIZE: 500MB
  MAX_REQUEST_SIZE: 500MB
  VCLIPPER_MAX_FILE_SIZE_BYTES: 524288000
  VCLIPPER_ALLOWED_FORMATS: mp4,avi,mov,wmv,flv,webm
  VCLIPPER_DOWNLOAD_EXPIRATION_MINUTES: 60
  VCLIPPER_RETRY_MAX_ATTEMPTS: 3
  VCLIPPER_RETRY_INITIAL_DELAY: 30
  VCLIPPER_RETRY_MAX_DELAY: 300
  LOG_LEVEL_ROOT: INFO
  LOG_LEVEL_VCLIPPER: DEBUG
  LOG_LEVEL_SPRING_WEB: INFO
  LOG_LEVEL_MONGODB: DEBUG

  AWS_REGION: us-east-1
  AWS_S3_BUCKET: vclipper-video-storage-prod
  AWS_SQS_PROCESSING_QUEUE_URL: https://sqs.us-east-1.amazonaws.com/879956639231/vclipper-video-processing-prod
  AWS_SQS_RESULT_QUEUE_URL: https://sqs.us-east-1.amazonaws.com/879956639231/vclipper-vclipping-results-prod
  AWS_SNS_NOTIFICATION_TOPIC_ARN: arn:aws:sns:us-east-1:879956639231:vclipper-video-processing-success-prod
  AWS_ACCOUNT_ID: 879956639231
  AWS_SESSION_TOKEN: ""
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""

  CORS_ALLOWED_ORIGINS: http://localhost:3000,http://127.0.0.1:3000,http://vclipper-frontend-prod.s3-website-us-east-1.amazonaws.com
