apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
type: Opaque
data:
  MONGODB_USER: {{ .Values.SECRET.DATABASE.MONGODB_USER | b64enc | quote }}
  MONGODB_PASSWORD: {{ .Values.SECRET.DATABASE.MONGODB_PASSWORD | b64enc | quote }}
  MONGODB_OPTIONS: {{ .Values.SECRET.DATABASE.MONGODB_OPTIONS | b64enc | quote }}
  DB_HOST: {{ .Values.SECRET.DATABASE.DB_HOST | b64enc | quote }}
  DB_PORT: {{ .Values.SECRET.DATABASE.DB_PORT | b64enc | quote }}
  APP_DB: {{ .Values.SECRET.DATABASE.APP_DB | b64enc | quote }}
  JWT_SECRET: {{ .Values.SECRET.JWT.SECRET | b64enc | quote }}
  JWT_EXPIRES: {{ .Values.SECRET.JWT.EXPIRES_IN | b64enc | quote }}
  RDS_HOST: {{ .Values.SECRET.DATABASE.RDS_HOST | b64enc | quote }}
  RDS_PASSWORD: {{ .Values.SECRET.DATABASE.RDS_PASSWORD | b64enc | quote }}
  RDS_DATABASE: {{ .Values.SECRET.DATABASE.RDS_DATABASE | b64enc | quote }}
  ORDER_SERVICE_URL: {{ .Values.SECRET.INTEGRATION.ORDER_SERVICE_URL | b64enc | quote }}
  AWS_ACCOUNT_ID: {{ .Values.SECRET.INTEGRATION.AWS_ACCOUNT_ID | b64enc | quote }}
  AWS_REGION: {{ .Values.SECRET.INTEGRATION.AWS_REGION | b64enc | quote }}
  AWS_SQS_PRODUCT_EVENTS_QUEUE_URL: {{ .Values.SECRET.INTEGRATION.AWS_SQS_PRODUCT_EVENTS_QUEUE_URL| b64enc | quote }}
  AWS_ENDPOINT_URL: {{ .Values.SECRET.INTEGRATION.AWS_ENDPOINT_URL | b64enc | quote }}
  AWS_ACCESS_KEY: {{ .Values.SECRET.INTEGRATION.AWS_ACCESS_KEY| b64enc | quote }}
  AWS_SECRET_KEY: {{ .Values.SECRET.INTEGRATION.AWS_SECRET_KEY| b64enc | quote }}
  AWS_SQS_POLLING_ENABLED: {{ .Values.SECRET.INTEGRATION.AWS_SQS_POLLING_ENABLED | b64enc | quote }}
  AWS_SQS_POLLING_DELAY_MS: {{ .Values.SECRET.INTEGRATION.AWS_SQS_POLLING_DELAY_MS | b64enc | quote }}
  AWS_SQS_MAX_MESSAGES: {{ .Values.SECRET.INTEGRATION.AWS_SQS_MAX_MESSAGES | b64enc | quote }}
  AWS_SQS_WAIT_TIME_SECONDS: {{ .Values.SECRET.INTEGRATION.AWS_SQS_WAIT_TIME_SECONDS| b64enc | quote }}
  LOG_LEVEL_ROOT: {{ .Values.SECRET.INTEGRATION.LOG_LEVEL_ROOT | b64enc | quote }}
  LOG_LEVEL_APP: {{ .Values.SECRET.INTEGRATION.LOG_LEVEL_APP | b64enc | quote }}
  LOG_LEVEL_WEB: {{ .Values.SECRET.INTEGRATION.LOG_LEVEL_WEB | b64enc | quote }}
  LOG_LEVEL_MONGODB: {{ .Values.SECRET.INTEGRATION.LOG_LEVEL_MONGODB | b64enc | quote }}
